# Generated by Django 3.0.6 on 2020-05-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
